version: 0.0
os: linux
file_exists_behavior: OVERWRITE

files:
  - source: /
    destination: /home/ubuntu/hello-jay-app

hooks:
  AfterInstall:
    - location: scripts/install_pm2.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/satart_pm2.sh
      timeout: 300
      runas: ubuntu
